### PR TITLE
Feat/quali_link

### PR DESCRIPTION
**Pull request by djmbritt**
Link qualifier and qualifications with each other.

### CODE REVIEW

**Comment by djmbritt** [comment]
image

image


image

image

**Review by laurensV — CHANGES_REQUESTED** [review]
seems like package-lock and package.json are not in sync: package.json effect-js is updated to 0.3.8, but in package-lock I still see 0.2.38

**Review by laurensV — CHANGES_REQUESTED** [review]
@djmbritt the package-lock.json has a conflict now with `main` branch, can you resolve it?

**Comment by djmbritt** [comment]
✅ Done

**Pull request merged**
